version: '2'

services:
  web:
    image: nginx:1.18.0-alpine
    ports:
    - "8080:80"
    volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
    - front

  php:
    image: php:8-fpm-alpine3.13
    volumes:
    - ./code:/code
    networks:
    - front
    - back

  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: xyz
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: xyz
    volumes:
    - ./seed:/docker-entrypoint-initdb.d
    - data:/var/lib/mysql
    networks:
    - back

  adminer:
    image: adminer:4.8.0
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
    - front
    - back

networks:
    front:
    back:

volumes:
  data:
